
#spring:
#  datasource:
#    source:
#      url: jdbc:postgresql://localhost:5432/migration
#      username: postgres
#      password: cisco
#      driver-class-name: org.postgresql.Driver
#    destination:
#      url: jdbc:postgresql://localhost:5432/migration_dest
#      username: postgres
#      password: cisco
#      driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#
#  batch:
#    jdbc:
#      initialize-schema: always
